openapi: 3.0.0
info:
  title: Pokemon Facts API
  description: A simple API that serves random Pokemon facts
  version: 1.0.0

servers:
  - url: https://pokefacts.vercel.app

paths:
  /:
    get:
      summary: Get Pokemon facts
      description: Retrieve random Pokemon facts or a specific fact by ID
      parameters:
        - in: query
          name: count
          schema:
            type: integer
            default: 1
          description: Number of random facts to retrieve
        - in: query
          name: id
          schema:
            type: integer
          description: ID of a specific fact to retrieve
        - in: query
          name: gen
          schema:
            type: integer
          description: Generation of Pokemon to filter facts (1-3)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: string
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Something went wrong!
